// Localized homepage FAQ (translated from the RU FAQ in index.html) for per-language
// home JSON-LD FAQPage. RU is read from index.html at prerender time; uz/en live here.

export const HOME_FAQ = {
  uz: [
  { q: "Oʻzbekistonda kimlar har yili majburiy auditdan oʻtishi shart?", a: "Oʻzbekiston Respublikasida majburiy auditdan quyidagilar oʻtadi: aksiyadorlik jamiyatlari, banklar va kredit tashkilotlari, sugʻurta kompaniyalari, investitsiya va pensiya jamgʻarmalari, birjalar, davlat ulushi 50% dan ortiq boʻlgan korxonalar, shuningdek tushum, aktivlar yoki xodimlar soni boʻyicha belgilangan chegaralardan oshib ketgan yirik kompaniyalar. Leader Audit OʻzR Moliya vazirligi litsenziyasiga ega va majburiy auditni xalqaro XAS standartlari boʻyicha oʻtkazadi." },
  { q: "Oʻzbekistonda QQS ni qanday qaytarib olish mumkin?", a: "Oʻzbekistonda QQS ni qaytarib olish kiruvchi QQS chiquvchi QQS dan oshib ketganda, tovar va xizmatlar eksport qilinganda, shuningdek investitsiya faoliyatida mumkin. Jarayon hujjatlarni tayyorlash, soliq organiga ariza topshirish, kameral tekshiruv oʻtkazish va qaytariladigan summani hisob-kitob raqamiga olishni oʻz ichiga oladi. Leader Audit mijozlarga 200 mlrd soʻmdan ortiq QQS ni qaytarib olishda koʻmaklashgan." },
  { q: "Tashabbusli audit nima va u nima uchun kerak?", a: "Tashabbusli (ixtiyoriy) audit kompaniya rahbariyatining qarori bilan moliyaviy hisobotning ishonchliligini baholash, soliq risklarini aniqlash, investitsiya jalb qilishga, biznesni sotishga yoki mulkdorni oʻzgartirishga tayyorgarlik koʻrish maqsadida oʻtkaziladi. Tashabbusli audit, ayniqsa, soliq tekshiruvidan oldin va xalqaro bozorlarga chiqishda juda foydali." },
  { q: "Toshkentda audit xizmatlari qancha turadi?", a: "Audit narxi kompaniya faoliyatining hajmiga, hisobotning murakkabligiga (XAS, MHXS, NSBU), tarmoqqa va xoʻjalik operatsiyalari soniga bogʻliq. Narxlar risklarni ekspress-tahlil qilgandan soʻng individual tarzda shakllantiriladi. Leader Audit birinchi konsultatsiyani bepul taqdim etadi — ariza qoldiring yoki +998 97 410 04 47 raqamiga qoʻngʻiroq qiling." },
  { q: "XAS NSBU dan nimasi bilan farq qiladi?", a: "XAS (Auditning xalqaro standartlari) — bu MHXS boʻyicha moliyaviy hisobotni auditdan oʻtkazishda qoʻllaniladigan, butun dunyoda eʼtirof etilgan global standartlardir. NSBU (Buxgalteriya hisobining milliy standartlari) — Oʻzbekiston Respublikasining barcha mahalliy kompaniyalar uchun majburiy boʻlgan standartlari. Oʻzbekistonda koʻplab kompaniyalar ikkala standart boʻyicha parallel hisob yuritadi, Leader Audit esa istalgan tizim boʻyicha audit oʻtkazadi." },
  { q: "Auditorlik kompaniyasi qanday javobgarlikka ega?", a: "Leader Audit auditorlik xulosasi sifati uchun toʻliq moddiy javobgarlikni oʻz zimmasiga oladi. Kasbiy javobgarlik Oʻzbekiston Respublikasi qonunchiligi talablariga muvofiq sugʻurtalangan — sugʻurta polisi auditorning kasbiy xatosi yuz bergan taqdirda mijozning zararini qoplashni kafolatlaydi." },
  { q: "Leader Audit qaysi tarmoqlar bilan ishlaydi?", a: "Leader Audit murakkab va tartibga solinadigan tarmoqlarda chuqur ekspertizaga ega: tibbiyot va farmatsevtika (Medical), IT va SaaS, ishlab chiqarish (Manufacturing), ulgurji va chakana savdo, qurilish, bank sektori, sugʻurta, investitsiya faoliyati, import-eksport. Kompaniya asoschilari CAP, CIPA va DipIFR (ACCA) malakalariga ega." },
  { q: "Kompaniya auditi qancha vaqt oladi?", a: "Kichik kompaniyaning standart auditi 2-3 hafta, oʻrta kompaniyaniki — 1-2 oy, filiallarga ega yirik kompaniyaniki — 2-4 oy davom etadi. Muddatlar hujjatlar hajmiga, hisob maʼlumotlarining tayyorligiga va tarmoqning murakkabligiga bogʻliq. Leader Audit auditorlik xulosasini mijoz bilan kelishilgan muddatlarda berishni kafolatlaydi." },
  { q: "Leader Audit kompaniya maʼlumotlarining maxfiyligini kafolatlaydimi?", a: "Maxfiylik nafaqat kasbiy etika bilan, balki yuridik jihatdan ham kafolatlanadi. Har bir mijoz bilan oshkor qilmaslik toʻgʻrisidagi kelishuv (NDA) imzolanadi, hujjatlarga kirish loyiha jamoasining tor doirasi bilan cheklanadi, fayllar almashinuvi himoyalangan kanallar orqali amalga oshiriladi. Maʼlumotni oshkor qilish faqat qonunda belgilangan hollarda davlat organlarining talabiga koʻra mumkin." },
  { q: "Leader Audit auditorlarida qanday xalqaro sertifikatlar bor?", a: "Leader Audit jamoasi CAP (Certified Accounting Practitioner), CIPA (Certified International Professional Accountant) va DipIFR (Diploma in International Financial Reporting, ACCA, Buyuk Britaniya) xalqaro malakalariga ega. Ushbu sertifikatlar MHXS, audit va soliqqa tortish sohasidagi ekspert darajasini tasdiqlaydi hamda xalqaro bozorlarda eʼtirof etiladi." },
  { q: "M&A bitimidan oldin faqat due diligence buyurtma qilish mumkinmi?", a: "Ha. Leader Audit M&A bitimlari va investitsiya raundlari oldidan moliyaviy, soliq va operatsion due diligence oʻtkazadi. DD doirasida yashirin risklar aniqlanadi, EBITDA normallashtiriladi, Quality of Earnings hisoboti va risklar reyestri tayyorlanadi. Loyihaning standart muddati — maqsadli kompaniyaning murakkabligiga qarab 4-8 hafta." },
  { q: "Oʻzbekiston IT-Park rezidentlari bilan ishlaysizmi?", a: "Ha, Leader Audit Oʻzbekiston IT-Park rezidentlari bilan ishlash tajribasiga ega. Biz IT-kompaniyalar uchun soliq imtiyozlarining xususiyatlarini, NMA (nomoddiy aktivlar) hisobining oʻziga xosligini, dasturiy taʼminot ishlab chiqish xarajatlarini IAS 38 va IFRS 38 boʻyicha kapitallashtirishni, IT-xizmatlar eksportidan daromadlarni tan olishni bilamiz. Investitsiya raundlari oldidan due diligence dan oʻtish uchun MHXS boʻyicha hisobot tayyorlaymiz." },
  ],
  en: [
  { q: "Who in Uzbekistan is required to undergo an annual audit?", a: "In the Republic of Uzbekistan, a mandatory audit is required for: joint-stock companies, banks and credit institutions, insurance companies, investment and pension funds, exchanges, enterprises with a state share exceeding 50%, as well as large companies that exceed the established thresholds for revenue, assets or headcount. Leader Audit holds a license from the Ministry of Finance of the Republic of Uzbekistan and performs mandatory audits in accordance with the International Standards on Auditing (ISA)." },
  { q: "How can you reclaim VAT in Uzbekistan?", a: "A VAT refund in Uzbekistan is available when input VAT exceeds output VAT, for the export of goods and services, and in connection with investment activities. The procedure involves preparing documentation, filing an application with the tax authority, undergoing a desk audit, and receiving the refund to your settlement account. Leader Audit has helped clients reclaim more than 200 billion soums in VAT." },
  { q: "What is a voluntary audit and why is it needed?", a: "A voluntary (initiative) audit is conducted at the decision of a company's management to assess the reliability of the financial statements, identify tax risks, and prepare for raising investment, selling the business, or changing ownership. A voluntary audit is especially useful ahead of a tax inspection and when entering international markets." },
  { q: "How much do audit services cost in Tashkent?", a: "The cost of an audit depends on the scale of the company's operations, the complexity of its financial statements (ISA, IFRS, NAS), the industry, and the volume of business transactions. Prices are determined individually following an express risk analysis. Leader Audit offers the first consultation free of charge — submit a request or call +998 97 410 04 47." },
  { q: "How do ISA differ from NAS?", a: "ISA (International Standards on Auditing) are global standards applied when auditing financial statements prepared under IFRS and are recognized worldwide. NAS (National Accounting Standards) are the standards of the Republic of Uzbekistan, mandatory for all local companies. Many companies in Uzbekistan maintain parallel accounting records under both frameworks, and Leader Audit performs audits under either system." },
  { q: "What liability does an audit firm bear?", a: "Leader Audit bears full financial liability for the quality of its audit report. Its professional liability is insured in accordance with the requirements of the legislation of the Republic of Uzbekistan — the insurance policy guarantees compensation for the client's losses in the event of a professional error by the auditor." },
  { q: "Which industries does Leader Audit work with?", a: "Leader Audit has deep expertise in complex and regulated industries: medicine and pharmaceuticals (Medical), IT and SaaS, manufacturing, wholesale and retail trade, construction, the banking sector, insurance, investment activities, and import-export. The firm's founders hold the CAP, CIPA and DipIFR (ACCA) qualifications." },
  { q: "How long does a company audit take?", a: "A standard audit of a small company takes 2-3 weeks, a medium-sized company 1-2 months, and a large company with branches 2-4 months. The timeline depends on the volume of documentation, the readiness of accounting data, and the complexity of the industry. Leader Audit guarantees delivery of the audit report within the timeframe agreed with the client." },
  { q: "Does Leader Audit guarantee the confidentiality of company data?", a: "Confidentiality is guaranteed not only by professional ethics but also legally. A non-disclosure agreement (NDA) is signed with every client, access to documents is limited to a small project team, and files are exchanged over secure channels. Information may be disclosed only at the request of government authorities in the cases established by law." },
  { q: "What international certifications do Leader Audit's auditors hold?", a: "The Leader Audit team holds the international qualifications CAP (Certified Accounting Practitioner), CIPA (Certified International Professional Accountant) and DipIFR (Diploma in International Financial Reporting from ACCA, United Kingdom). These certifications confirm an expert level of competence in IFRS, auditing and taxation and are recognized in international markets." },
  { q: "Can I order only due diligence ahead of an M&A deal?", a: "Yes. Leader Audit performs financial, tax and operational due diligence ahead of M&A deals and investment rounds. As part of the due diligence, hidden risks are identified, EBITDA is normalized, and a Quality of Earnings report and a risk register are prepared. The standard project timeline is 4-8 weeks, depending on the complexity of the target company." },
  { q: "Do you work with residents of IT Park Uzbekistan?", a: "Yes, Leader Audit has experience working with residents of IT Park Uzbekistan. We understand the specifics of tax incentives for IT companies, the accounting treatment of intangible assets, the capitalization of software development costs under IAS 38 / IFRS, and the recognition of revenue from the export of IT services. We prepare IFRS financial statements for due diligence ahead of investment rounds." },
  ],
};
